### ISSUE TITLE
"TypeError: this.mapData is not a function" With Pulse 2.2 and Vue

### ISSUE THREAD

**Issue by Pckool** [pulse-framework/pulse#56]
I just updated to Pulse 2.2 and there is an issue with Vue js integration. It fais with
```javascript
data() {
   return {
       ...this.mapData({
           something: 'test/me', 
       });
   }
}
```

## Expected Behavior
It should run just fine.

## Current Behavior
The app fails and throws error:
```
[Vue warn]: Error in data(): "TypeError: this.mapData is not a function"
```

## Extra Information
N/A

## Environment Information
- Operating System: `Windows 10 x64 Pro`
- Browser Version (If applicable): `Brave`
- Pulse Version: `2.2.0`
- Framework/Framework Version (If applicable): `2.6.11`

**Comment by jamiepine** [comment]
Just to make sure, as you now need to pass the `Vue` constructor as the value of `framework` in the config instead of just a string `'vue'`.

Another way to do this is with the new `Pulse.use(Vue)` anywhere before `new Vue`.

Currently you will still need to call `Vue.use(Pulse)`, make sure thats after though.

```js
import Pulse from 'pulse-framework'
import Vue from 'vue'

Pulse.use(Vue);
Vue.use(Pulse);

export const core = new Pulse();

export default new Vue();
```

I might look into making `Pulse.use(Vue)` automatically run `Vue.use(Pulse)`... I'll report back if that's possible and sneak it into 2.2 before npm release

**Comment by Pckool** [comment]
This is how my pulse file looks: 
```javascript
import Pulse from 'pulse-framework';
import Vue from 'vue';

Pulse.use(Vue);

export default new Pulse({
    config: {
        framework: Vue,
        mapDataUnderPropName: 'pulse',
        baseModuleAlias: true
    },
...
})
```

My main index.js file (or my master js file for vue)

```javascript
import Vue from 'vue';
import Pulse from './js/pulse.js';
...
Vue.use(Pulse);
...
```

Is that not how it is supposed to be configured?
